// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agendarcitas.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230524015419_v01")]
    partial class v01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Citas.Agendar_citas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Agendar_citas");
                });

            modelBuilder.Entity("Citas.Cliente", b =>
                {
                    b.Property<int>("cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Citaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("telefono")
                        .HasColumnType("INTEGER");

                    b.HasKey("cedula");

                    b.HasIndex("Citaid");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Citas.Cliente", b =>
                {
                    b.HasOne("Citas.Agendar_citas", "Cita")
                        .WithMany("cliente")
                        .HasForeignKey("Citaid");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("Citas.Agendar_citas", b =>
                {
                    b.Navigation("cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
